# Produce a source tree that builds on a machine that has never seen the
# internet.
#
# You do NOT need this to build offline here: `cargo build --offline` already
# works, because every dependency is in the local registry cache under
# ~\.cargo\registry. Run this only when moving the crate to an air-gapped
# machine, where that cache does not exist.
#
# It writes ~300 MB into vendor\ and points cargo at it. Both are gitignored:
# committing a third of a gigabyte of other people's code is not versioning.

$ErrorActionPreference = 'Stop'
$crate = Split-Path -Parent $PSScriptRoot
Set-Location $crate

Write-Host "vendoring dependencies (needs network, once)..."
cargo vendor | Out-Null

New-Item -ItemType Directory -Force -Path "$crate\.cargo" | Out-Null
@'
# Generated by tools\vendor.ps1 -- resolve crates from vendor\, never the network.
[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
'@ | Set-Content -Encoding utf8 "$crate\.cargo\config.toml"

Write-Host "done. copy this directory anywhere and run:"
Write-Host "  cargo build --release --offline"
